---
#### 1) Install NRPE on ALL CLIENTS ####
#### 1) Install NRPE and monitoring plugins ####
- name: Install NRPE and monitoring agent
  hosts: "clients:!nagios"
  become: yes
  tasks:

    - name: Ensure required Nagios directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: nagios
        group: nagios
        mode: '0755'
      loop:
        - /var/run/nagios
        - /var/log/nagios
        - /var/spool/nagios
        - /var/spool/nagios/cmd

    - name: Remove stale PID file if exists
      file:
        path: /var/run/nagios/nagios.pid
        state: absent

    - name: Fix ownership of main Nagios folders
      file:
        path: "{{ item }}"
        state: directory
        recurse: yes
        owner: nagios
        group: nagios
      loop:
        - /var/run/nagios
        - /var/log/nagios
        - /var/spool/nagios


    - name: Install NRPE and basic plugins
      dnf:
        name:
          - nrpe
          - nagios-plugins-ping
          - nagios-plugins-load
          - nagios-plugins-disk
          - nagios-plugins-procs
          - nagios-plugins-users
          - nagios-plugins-http
        state: present

    - name: Allow Nagios server IP access
      lineinfile:
        path: /etc/nagios/nrpe.cfg
        regexp: '^allowed_hosts='
        line: 'allowed_hosts=127.0.0.1,192.168.220.206'

    - name: Create custom NRPE commands directory
      file:
        path: /etc/nagios/nrpe.d
        state: directory
        owner: nagios
        group: nagios
        mode: '0755'

    - name: Deploy NRPE check commands
      copy:
        src: files/nrpe_local.cfg
        dest: /etc/nagios/nrpe.d/nrpe_local.cfg
        mode: '0644'

    - name: Restart NRPE
      service:
        name: nrpe
        enabled: yes
        state: restarted



#### 2) Install and Configure Nagios Server ####
- name: Install and configure Nagios main server
  hosts: nagios
  become: yes
  tasks:
    - name: Install Nagios Core and plugins
      dnf:
        name:
          - nagios
          - nagios-plugins-all
          - nagios-plugins-nrpe
          - httpd
          - php
          - php-cli
          - httpd-tools
        state: present

    - name: Add nagiosadmin web user
      command: htpasswd -bc /etc/nagios/passwd nagiosadmin Nagios123!
      args:
        creates: /etc/nagios/passwd

    - name: Deploy monitored host definitions
      copy:
        src: files/clients.cfg
        dest: /etc/nagios/objects/clients.cfg
        mode: '0644'

    - name: Deploy service check definitions
      copy:
        src: files/services.cfg
        dest: /etc/nagios/objects/services.cfg
        mode: '0644'

    - name: Ensure Nagios reads new config files
      lineinfile:
        path: /etc/nagios/nagios.cfg
        insertafter: EOF
        line: "{{ item }}"
      loop:
        - "cfg_file=/etc/nagios/objects/clients.cfg"
        - "cfg_file=/etc/nagios/objects/services.cfg"

    - name: Validate Nagios Configuration
      command: /usr/sbin/nagios -v /etc/nagios/nagios.cfg
      register: validation
      ignore_errors: true

    - name: Print validation output for debugging
      debug:
        var: validation.stdout_lines

    - name: Fail if Nagios config is invalid
      fail:
        msg: "Nagios configuration invalid — check errors above"
      when: validation.rc != 0

    - name: Enable and start services
      service:
        name: nagios
        state: restarted
        enabled: yes

    - name: Start Apache service
      service:
        name: httpd
        state: restarted
        enabled: yes
